### ISSUE TITLE
Mongo cursor lost on a long run

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#174]
Возможно, имеет значение, что я редактировал документ из аудита, который был в процессе, но есть и подозрение на таймаут соединения с Mongo.

```
Traceback (most recent call last):
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 27, in <module>
    main()
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 20, in main
    runner.run()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/runner.py", line 189, in run
    for document in documents:
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1093, in _refresh
    self.__send_message(g)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 955, in __send_message
    address=self.__address)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
    exhaust=exhaust)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
    unpack_res)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(first)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/helpers.py", line 156, in _check_command_response
    raise CursorNotFound(errmsg, code, response)
pymongo.errors.CursorNotFound: cursor id 7854582803017354618 not found
```

**Comment by compartia** [comment]
if not related, probably could be fixed in same transaction

```
.....finalizing audit 5edbc586da3678279fbcabe0
Traceback (most recent call last):
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 27, in <module>
    main()
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 20, in main
    runner.run()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/runner.py", line 199, in run
    finalizer.finalize()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 380, in finalize
    contracts = get_docs_by_audit_id(audit["_id"], 15, "CONTRACT")
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 67, in get_docs_by_audit_id
    for doc in res:
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1073, in _refresh
    self.__send_message(q)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 955, in __send_message
    address=self.__address)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
    exhaust=exhaust)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
    unpack_res)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(first)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

Process finished with exit code 1
```
