### ISSUE TITLE
Finalyzer fails if there's no date in contract

### ISSUE THREAD

**Issue by compartia** [nemoware/analyser#176]
```
Traceback (most recent call last):
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 27, in <module>
    main()
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 20, in main
    runner.run()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/runner.py", line 199, in run
    finalizer.finalize()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 369, in finalize
    violations.extend(check_contract(contract, charters, protocols, audit))
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 206, in check_contract
    {"contract": {"id": contract["_id"], "number": contract_number, "type": contract["parse"]["documentType"], "date": contract_attrs["date"]["value"]},
KeyError: 'date'

```

**Comment by SergeyShalaevsky** [comment]
как такой док вообще сюда просочился? надо смотреть json этого дока

**Comment by compartia** [comment]
этот я уже вот тем коммитом выше поправил, но вообще в базе могут болтаться доки, старыми версиями паршенные, и можно финалайзер, видимо, обложить трайкэтчами

**Comment by SergeyShalaevsky** [comment]
меня смущает, то что он вообще до туда дошел.
запрос в монгу на доки имеет вид:
    query = {
        'auditId': id,
        'parse.documentType': kind,
        "state": state,
        "$or": [
            {"analysis.attributes.date": {"$ne": None}},
            {"user.attributes.date": {"$ne": None}}
        ]
    }
вот я и хочу понять, почему этот док пролез через него

**Comment by compartia** [comment]
есть некоторая вероятность что я его отредактировал через ui после того, как кверя отработала, но до того, как финалайзер все доделал.

**Comment by SergeyShalaevsky** [comment]
это очень маловероятно, т.к. доки читаются все сразу и финалайзер их потом не перечитывает.

**Comment by compartia** [comment]
```
.....finalizing audit 5de8a3f61b3453848224a9c3
.....audit 5de8a3f61b3453848224a9c3 is waiting for approval
.....finalizing audit 5dee80424ddc27bcf92dd87c
Traceback (most recent call last):
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 27, in <module>
    main()
  File "/Users/artem/work/nemo/goil/nlp_tools/bin/analyser_run.py", line 22, in main
    schedule.run_pending()
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/Users/artem/work/nemo/goil/nlp_tools/venv/lib/python3.7/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/runner.py", line 208, in run
    finalizer.finalize()
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 395, in finalize
    violations.extend(check_contract(contract, charters, protocols, audit))
  File "/Users/artem/work/nemo/goil/nlp_tools/analyser/finalizer.py", line 205, in check_contract
    if charter_attrs["date"]["value"] <= contract_attrs["date"]["value"]:
TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'

```

**Comment by SergeyShalaevsky** [comment]
это очередная проблема сохранения пользовательской разметки в ui
